import clsx from 'clsx';
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';

import './globals.css';
import { HeaderSkeleton } from '@/UI/seletons';
import RootProvider from '@/layouts/providers/RootProvider';
import { formatTimeAgo } from '@/lib/formatTimeAgo';
import { getPosts } from '@/lib/getPosts';

const Header = dynamic(() => import('@/components/Header'), {
  loading: () => <HeaderSkeleton />,
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
};

// warning Status modal when you create the post and the post with this title already exist
// report comments list
// Footer
// Home page some Slider, info ...,  last 3-6 posts,
// add likes to the post

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      {/* <body className={clsx(inter.className, 'bg-[#282828]')}> */}
      <RootProvider>
        <body className={inter.className}>
          <Header />
          <div
            className={clsx('w-full pt-[72px] px-[3%]', 'sm:px-[5%]', 'lg:px-[10%] xl:px-[15%]')}
          >
            {children}
          </div>
          <div id='modals'></div>
        </body>
      </RootProvider>
    </html>
  );
}
