import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import dynamic from 'next/dynamic';

import { HeaderSkeleton } from '@/UI/skeletons';
import RootProvider from '@/layouts/providers/RootProvider';
import Footer from '@/components/Footer';
import Wrapper from '@/layouts/wrapper';

const Header = dynamic(() => import('@/components/Header'), {
  loading: () => <HeaderSkeleton />,
});
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
};

// faster like and unlike animation ??
// dashboard skeleton
// add to each modal onResize event to remove a modal window
// Home page some Slider, info ...,  last 3-6 posts,

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <RootProvider>
        <body className={inter.className}>
          <Header />
          <Wrapper>
            <div style={{ paddingTop: 72 }} className='min-h-screen'>
              {children}
            </div>
          </Wrapper>
          <Footer />
          <div id='modals'></div>
        </body>
      </RootProvider>
    </html>
  );
}
